import { Mud } from "./Mud";
import { Glass } from "./Glass";
import { Air } from "./Air";
import { Brick } from "./Brick";
import { Door } from "./Door";
import { Glowstone } from "./Glowstone";
import { Gold } from "./Gold";
import { Ice } from "./Ice";
import { Lava } from "./Lava";
import { Window } from "./Window";
import { Wall } from "./Wall";
let wall = new Wall();
let air = new Air();
let brick = new Brick();
let door = new Door(2, "Mordor", "black", 60);
let glass = new Glass(80);
let glowstone = new Glowstone();
let window = new Window(2, " Asgard", "light-gray", 90, " Can ");
let mud = new Mud();
let gold = new Gold(50);
let lava = new Lava();
let glowstone2 = new Glowstone();
let ice = new Ice();
let lava2 = new Lava();
let gold2 = new Gold(30);
let ice2 = new Ice();

wall.placeBlock(air);
wall.placeBlock(brick);
wall.placeBlock(door);
wall.placeBlock(glass);
wall.placeBlock(glowstone);
wall.placeBlock(window);
wall.placeBlock(mud);
wall.placeBlock(gold);
wall.placeBlock(lava);
wall.placeBlock(glowstone2);
wall.placeBlock(ice);
wall.placeBlock(lava2);
wall.placeBlock(gold2);
wall.placeBlock(ice2);

wall.calculateLightTransmission();
wall.printStatus();
